### ISSUE TITLE
Feature: Auth - SERVER

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/VIRTUAL-PET#1]
# AUTH FEATURE- SERVER-SIDE

> In order to achieve and close this epic, we must satisfy:

- [x] Create User Modal/Schema
- [x] Create Register Route
- [x] Encrypt password
- [x] Validate `req.body`
- [x] Store User in DB
- [x] Generate Token
- [x] Send Appropriate response to the client including token
- [x] Create Login Route
- [x] Decrypt password
- [x] Validate `req.body`
- [x] Find User in DB
- [x] Generate token
- [x] Send Appropriate response to the client including token
- [x] Register: 422, 409, 401, 500, 201
- [x] Login: 404, 422, 403, 500, 200
