### ISSUE TITLE
login-page

### ISSUE THREAD

**Issue by harrisxo** [Medic1111/VIRTUAL-PET#10]
- [x] change the font family for input
- [x] change the font family for buttons 
- [x] change font size of button text
- [x] change input border transperancy slightly
