### ISSUE TITLE
RegisterForm component - EPIC 

### ISSUE THREAD

**Issue by aruadecarvalho** [Medic1111/VIRTUAL-PET#16]
- [x] Create RegisterForm component with the same input as LoginForm
- [x] Create registerFormData state
- [x] Create handleSubmitRegister
- [x] Create new button slide down animation
