### ISSUE TITLE
HOME PAGE - CLIENT SIDE

### ISSUE THREAD

**Issue by aruadecarvalho** [Medic1111/VIRTUAL-PET#4]
> In order to achieve and close this epic, we must satisfy:

- [x] Find logo
- [x] Find font for home
- [x] Structure the home page
- [x] Style the home page

**Comment by aruadecarvalho** [comment]
Done!
