### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by harrisxo** [Medic1111/VIRTUAL-PET#8]
- [x] Add input for Login and Password
- [x] Add ColorScheme 
- [x] Match style and font with Landing/Home 
- [x] Add Animation to Login button (enhancement)
- [x] Add Authentication
